# Android Makefile for CYGWIN by Rikku2000

# Note: To create a apk file enter: "make APP=sdlpal".

# Build the Project and make Release
make:
	$(ANDROID_NDK_ROOT)/ndk-build
#	$(ANT_ROOT)/ant debug
	$(ANT_ROOT)/ant release

# Clean the Project
clean:
	$(ANDROID_NDK_ROOT)/ndk-build clean
